#!/bin/bash

set -e

source /usr/local/lib/entrypoint.sh
source /usr/local/lib/ldaputils.sh

if [[ -z $2 || -n $3 ]] ; then
	echo "usage $0 <name> <uidNumber>" >&2
	echo "ex: $0 test 1000" >&2
	exit 1
fi

fail_if_admin "$1"

name="${1,,}"
gid=513
dn="cn=${name},ou=users,${olcSuffix}"
uidNumber=$2

log "Creating user: $dn ..."
read_password
cat <<- EOF | ldapadd -d 256 -D "$olcRootDN" -H ldapi:// -w "$(<$secret)" -x
	dn: ${dn}
	cn: ${name}
	gidNumber: ${gid}
	homeDirectory: /home/${name}
	loginShell: /bin/bash
	objectClass: account
	objectClass: posixAccount
	objectClass: shadowAccount
	objectClass: top
	shadowLastChange: $(echo $(date "+%s")/60/60/24 | bc)
	shadowMax: 999
	uid: ${name}
	uidNumber: ${uidNumber}
	userPassword: ${PASSWORD_HASH}
EOF

log "Altered Configuration:"
ldapsearch -b "$dn" -H ldapi:// -LLL -Q -Y EXTERNAL -ZZ

log "Testing ..."
ldapwhoami -D "$dn" -H ldapi:// -w "$PASSWORD" -x -ZZ

