#!/bin/bash

set -e -o pipefail

source /usr/local/lib/entrypoint.sh
source /usr/local/lib/ldaputils.sh

if [[ -z "${2}" || -n "${4}" ]] ; then
	echo "usage ${0} <user name> [ <action=add|delete|list> [ <group name> ] ]" >&2
	echo "ex: ${0} myuser" >&2
	echo "ex: ${0} myuser add mygroup" >&2
	exit 1
fi

fail_if_admin "${1}"

user="${1,,}"
action="${2:-list}"
group="${3,,}"
dn="cn=${group},ou=groups,${olcSuffix}"

if [[ "${action}" != "add" && "${action}" != "delete" && "${action}" != "list" ]] ; then
	echo "Unsupported action: ${action}" >&2
	exit 1
fi

log "Existing configuration:"
ldapsearch -b "${dn}" -H ldapi:// -LLL -Q -Y EXTERNAL -ZZ

[[ "${action}" == "list" ]] && exit 0

cat <<- EOF | ldapmodify -d 256 -D "${olcRootDN}" -H ldapi:// -x -w "$(<"${secret}")"
	dn: ${dn}
	changetype: modify
	${action}: memberuid
	memberuid: ${user}
EOF

log "Altered configuration:"
ldapsearch -b "${dn}" -H ldapi:// -LLL -Q -Y EXTERNAL -ZZ

