#!/bin/bash

set -e

source /usr/local/lib/entrypoint.sh
source /usr/local/lib/ldaputils.sh

if [[ -z $2 || -n $3 ]] ; then
	echo "usage $0 <name> <gidNumber>" >&2
	echo "ex: $0 users 513" >&2
	exit 1
fi

fail_if_admin "$1"

name="${1,,}"
dn="cn=${name},ou=groups,${olcSuffix}"
gidNumber=$2

log "Creating group: $dn ..."
cat <<- EOF | ldapadd -d 256 -D "$olcRootDN" -H ldapi:// -w "$(<$secret)" -x
	dn: ${dn}
	cn: ${name}
	gidNumber: ${gidNumber}
	objectClass: posixGroup
	objectClass: top
EOF

log "Altered Configuration:"
ldapsearch -b "$dn" -H ldapi:// -LLL -Q -Y EXTERNAL -ZZ

