#!/bin/bash

set -e -o pipefail

source /usr/local/lib/entrypoint.sh
source /usr/local/lib/ldaputils.sh

if [[ -n "${1}" ]] ; then
	echo "usage ${0}" >&2
	exit 1
fi

dn="${olcRootDN}"

log "You are about to ${BOLD_RED}RESET${NC} the password for: ${BOLD_RED}${dn}${NC}"
prompt_continue

log "Existing configuration:"
# https://wiki.debian.org/LDAP/OpenLDAPSetup#Administrator_Access
#ldapsearch -b "${dn}" -H ldapi:// -LLL -Q -Y EXTERNAL -ZZ
tmp=$(grep "olcRootPW" "${SLAPD_CONFIG}/slapd.d/cn=config/olcDatabase={1}mdb.ldif")
echo -e "${YELLOW}${tmp}${NC}"
echo ""

read_password
echo "${PASSWORD}" > "${secret}"

cat <<- EOF | ldapmodify -d 256 -H ldapi:// -Q -Y EXTERNAL
	dn: olcDatabase={1}mdb,cn=config
	changetype: modify
	replace: olcRootPW
	olcRootPW: ${PASSWORD_HASH}
EOF

log "Altered configuration:"
#ldapsearch -b "${dn}" -H ldapi:// -LLL -Q -Y EXTERNAL -ZZ
tmp=$(grep "olcRootPW" "${SLAPD_CONFIG}/slapd.d/cn=config/olcDatabase={1}mdb.ldif")
echo -e "${YELLOW}${tmp}${NC}"

log "Testing ..."
ldapwhoami -D "${dn}" -H ldapi:// -w "$(<"${secret}")" -x -ZZ

